# Project information
site_name: <PACKAGE_NAME>
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: <SITE_AUTHOR>
site_description: >-
  A library for rendering YouTube and reference sites in Jupyter notebooks

# Repository
repo_name: <GITHUB_USER_NAME>/<REPO_NAME>
repo_url: https://github.com/<GITHUB_USER_NAME>/<REPO_NAME>

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/<GITHUB_USER_NAME>
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<GITHUB_USER_NAME>
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<GITHUB_USER_NAME>
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/<GITHUB_USER_NAME>/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; <YEAR> <a href="https://github.com/<GITHUB_USER_NAME>"  target="_blank" rel="noopener"><AUTHOR_NAME></a>